[package]
name = "prometheus-sd-nexthop"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
futures = "0.3.31"
rtnetlink = "0.18.1"
tokio = { version = "1.0.1", features = ["macros", "rt", "rt-multi-thread", "time"] }
